```{r knit2synapse, include=FALSE, eval=FALSE}
library(rGithubClient)
library(synapseClient)
synapseLogin()

thisRepo <- getRepo('kdaily/MEP_LINCS',
                    ref='branch', refName='prereleasewiki')
thisScript <- getPermlink(thisRepo, 'prereleaseWiki.Rmd')

knit2synapse::knitToFolderEntity(file='./prereleaseWiki.Rmd', parentId = "syn2862345",
                                 folderName = "Pre-release", overwrite=TRUE,
                                 executed=thisScript)
```

```{r setup, include=FALSE}
library(plyr)
library(dplyr)
library(data.table)
library(stringr)
library(tidyr)
library(reshape2)
library(knitr)
library(synapseClient)
synapseLogin()

set.seed(4)

knitr::opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE)

```
## Annotated Data
```{r annotatedfilesquery}
annotatedFolder <- "syn5004301"
query <- sprintf('select id,name,level,CellLine,StainingSet from file where parentId=="%s"', 
                 annotatedFolder)
annotFiles <- synQuery(query)

colnames(annotFiles) <- gsub(".*\\.", "", colnames(annotFiles))

paramFiles <- annotFiles %>% filter(level == "PipelineParameters")
annotFiles <- annotFiles %>% filter(level != "PipelineParameters")

```
```{r annotatedfilestable, results='asis'}
annotFiles %>% 
  dcast(CellLine + StainingSet ~ level, value.var = "id") %>% 
  kable
```
## Raw Data
```{r rawfilesquery}
rawFolder <- "syn4997435"
query <- sprintf(paste('select id,name,level,CellLine,StainingSet,Barcode,Location,Well',
                       'from file where parentId=="%s"'), 
                 rawFolder)

rawFiles <- synQuery(query, blockSize = 400)$collectAll()

colnames(rawFiles) <- gsub(".*\\.", "", colnames(rawFiles))
```
```{r rawfilestable, results='asis'}
rawFilesTbl <- dcast(rawFiles, 
                     Barcode + CellLine + StainingSet + Location ~ Well, 
                     value.var = "id")
```

```{r rawdatatable}
kable(rawFilesTbl)
```

